on: 
  push:
    branches: 
      - rust

name: Docker Publish

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      publish-server: ${{ steps.set-output.outputs.publish-server }}
      publish-client: ${{ steps.set-output.outputs.publish-client }}
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y jq

      - name: Check Clone Depth
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        run: |
          export FETCH_DEPTH=$(echo $COMMITS | jq length)

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: $FETCH_DEPTH

      - name: Checkout submodules
        run: |
          git submodule update --init --depth $FETCH_DEPTH -- client server

      - name: Check Git Diff & Log
        id: set-output
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
        run: |
          if [[ $(git diff --name-only $BEFORE $AFTER server) ]]; then
            echo "::set-output name=publish-server::true"
          fi
          if [[ $(git diff --name-only $BEFORE $AFTER client) ]]; then
            echo "::set-output name=publish-client::true"
          fi
          $GIT_LOG=$(git log --pretty=format:"%s %b" $BEFORE..$AFTER)
          if [ $GIT_LOG ?? 'publish-server' ]
            echo "::set-output name=publish-server::true"
          fi
          if [ $GIT_LOG ?? 'publish-client' ]
            echo "::set-output name=publish-client::true"
          fi

  publish-server:
    needs: prepare
    if: ${{ needs.prepare.outputs.publish-server }}
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set-output.outputs.success }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: $FETCH_DEPTH

      - name: Checkout submodules
        run: |
          git submodule update --init --depth $FETCH_DEPTH -- client server

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd server
          bash publish.sh

      - name: Set output to success
        id: set-output
        run: |
          echo "::set-output name=success::true"

  publish-client:
    needs: prepare
    if: ${{ needs.prepare.outputs.publish-client }}
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set-output.outputs.success }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: $FETCH_DEPTH

      - name: Checkout submodules
        run: |
          git submodule update --init --depth $FETCH_DEPTH -- client server

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd client
          bash publish.sh

      - name: Set output to success
        id: set-output
        run: |
          echo "::set-output name=success::true"

  publish:
    needs: [prepare, publish-server, publish-client]
    if: |
      (${{ needs.prepare.outputs.publish-server }} && ${{ needs.publish-server.outputs.success }}) ||
      (${{ needs.prepare.outputs.publish-client }} && ${{ needs.publish-client.outputs.success }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: bash publish.sh
